### PR TITLE
Evaluation is complete - Move to Dev for final checks and integration

### PR DESCRIPTION
**Pull request by MaxCunningham19**

### CODE REVIEW

**Review by MaxCunningham19 — COMMENTED** [review]
Reviewed

**Comment by MaxCunningham19** [comment]
@taylorj8 can you review and merge these branches before we make any final changes in the development branch

**Review by taylorj8 — DISMISSED** [review]
Ready to merge once conflicts resolved

**Comment by taylorj8** [comment]
Conflicts resolved - ready to merge

**Pull request merged**
